current_parameters_file: config_goce/electric_current_parameters.h5
goce_column_description_file: ./GOCE-TLM-packets-description.xlsx

train_config:
  use_pinn: True
  use_amps: True
  filter_std: True
  filter_correlation: True
  training_file_path: 'config_goce/'
  test_split: 0.2
  neural_network_variant: 3 #0
  learn_config:
    epochs: 100
    batch_size: 1500
    learning_rate: 0.01
    optimizer: 'adam'
    loss: 'mean_squared_error'
    first_extra: 0 #50
    drop_every: 90

cdf_config:
  cdf_path: '/Volumes/Crucial X8/'
  cdf_template_path: './templates/goce_ml_'
  version: '0301'
  sat_suffix: 'GO'

y_all_feature_keys: [ 'CHAOS_B_FGM1_0', 'CHAOS_B_FGM1_1', 'CHAOS_B_FGM1_2' ]
meta_features: [ 'RAW_Timestamp', 'KP_Timestamp',
                      'APEX_QD_LAT', 'APEX_QD_LON', 'APEX_MLT', 'RAW_Longitude', 'RAW_Latitude',
                      'q1', 'q2', 'q3', 'q4',
                      'FGM1_X_sc', 'FGM1_Y_sc', 'FGM1_Z_sc',
                      'FGM1_X_nec', 'FGM1_Y_nec', 'FGM1_Z_nec',
                      'chaos7_b_nec_x', 'chaos7_b_nec_y', 'chaos7_b_nec_z',
                      'chaos7_b_lit_nec_y', 'chaos7_b_lit_nec_z', 'chaos7_b_lit_nec_x',
                      'chaos7_b_ext_nec_x', 'chaos7_b_ext_nec_y', 'chaos7_b_ext_nec_z',
                      'chaos7_b_cor_nec_x', 'chaos7_b_cor_nec_y', 'chaos7_b_cor_nec_z',
                      'X', 'Y', 'Z', 'VX', 'VY', 'VZ', 'r.trs',
                      'KP', 'Dst', 'F10.7', 'F10.7-81d',
                      'ORB_OrbitNo', 'q1_fgm32nec', 'q2_fgm32nec', 'q3_fgm32nec', 'q4_fgm32nec',
                      'q1_fgm22nec', 'q2_fgm22nec', 'q3_fgm22nec', 'q4_fgm22nec',
                      'q1_fgm12nec', 'q2_fgm12nec', 'q3_fgm12nec', 'q4_fgm12nec',#'nan_share_FLAG',
                      'By', 'Bz', 'Sw', 'By-20m', 'Bz-20m', 'Sw-20m', 'tilt',
                      'amps_b_mag_x', 'amps_b_mag_y', 'amps_b_mag_z', 'amps_b_nec_x', 'amps_b_nec_y', 'amps_b_nec_z',
                      'Spaceweather_Flag', 'HP_Timestamp', 'Hp30',
                 'Magnetic_Activity_Flag', 'Outlier_Flag', 'Interpolation_Distance_Flag', 'DOY',
                 'weightings', 'NaN_Flag',

  #'kp_sel',
  #'mlt', 'lon.trs',
  #'ORB_Timestamp', 'ORB_Latitude', 'ORB_Longitude', 'ORB_Radius', 'ORB_MLT'
  #  'gps_sec', 'q1_fgm32nec', 'q2_fgm32nec', 'q3_fgm32nec', 'q4_fgm32nec', 'lt', 'mjd2000', 'qdlon', 'mlat', 'q1_fgm12nec', 'q2_fgm12nec', 'q3_fgm12nec',
  # 'q4_fgm12nec', 'q1_fgm22nec', 'q2_fgm22nec', 'q3_fgm22nec',
  # 'q4_fgm22nec', 'chaos7_b_fgm2_x', 'chaos7_b_fgm2_y', 'chaos7_b_fgm2_z',
  # 'chaos7_b_fgm3_x', 'chaos7_b_fgm3_y', 'chaos7_b_fgm3_z',
  # 'chaos7_b_sc_x', 'chaos7_b_sc_y', 'chaos7_b_sc_z', 'FGM2_X_sc', 'FGM2_Y_sc', 'FGM2_Z_sc', 'FGM3_X_sc', 'FGM3_Y_sc',
  # 'FGM3_Z_sc',
  # 'FGM2_X_nec', 'FGM2_Y_nec', 'FGM2_Z_nec', 'FGM3_X_nec', 'FGM3_Y_nec',
  # 'FGM3_Z_nec', 'chaos7_b_lit_nec_y', 'chaos7_b_lit_nec_z', 'chaos7_b_ext_nec_x',
  # 'chaos7_b_ext_nec_y', 'chaos7_b_ext_nec_z',  'chaos7_b_cor_nec_x', 'chaos7_b_cor_nec_y', 'chaos7_b_cor_nec_z',
  # 'chaos7_b_lit_nec_x'
]

essential_calibration_keys: [ 'q1', 'q2', 'q3', 'q4', 'MHT00000', 'PHD94001', 'PHD94002', 'PHD94003', 'PHD94004', 'PHD94005',
                                  'PHD94006', 'PHD95002', 'PHD95021', 'PHT10040', 'PHT10060', 'PHT11960', 'PHT11980', 'PHT12100',
                                  'PHT12120', 'PHT12140', 'PHT12280', 'PHT12300', 'PHT12320', 'PHT12420', 'PHT12440', 'PHT12460',
                                  'PHT12560', 'PHT12580', 'PHT12600', 'THT00004', 'THT00012', 'THT00068', 'THT10000', 'THT10001',
                                  'THT10002', 'THT10003', 'THT10004', 'THT10005', 'FGM1_X', 'FGM1_Y', 'FGM1_Z', 'FGM2_X',
                                  'FGM2_Y', 'FGM2_Z', 'FGM3_X', 'FGM3_Y', 'FGM3_Z', 'fgm_gapsize', 'mtr1_current', 'mtr2_current',
                                  'mtr3_current', 'X', 'Y', 'Z', 'VX', 'VY', 'VZ', 'r.trs', 'lat.trs', 'lon.trs',
                                  'chaos7_b_nec_x', 'chaos7_b_nec_y', 'chaos7_b_nec_z', 'chaos7_b_cor_nec_x',
                                  'chaos7_b_cor_nec_y', 'chaos7_b_cor_nec_z', 'chaos7_b_lit_nec_x', 'chaos7_b_lit_nec_y',
                                  'chaos7_b_lit_nec_z', 'chaos7_b_ext_nec_x', 'chaos7_b_ext_nec_y', 'chaos7_b_ext_nec_z',
                                  'FGM1_X_nec', 'FGM1_Y_nec', 'FGM1_Z_nec', 'FGM2_X_nec', 'FGM2_Y_nec', 'FGM2_Z_nec',
                                  'FGM3_X_nec', 'FGM3_Y_nec', 'FGM3_Z_nec', 'FGM1_X_sc', 'FGM1_Y_sc', 'FGM1_Z_sc', 'FGM2_X_sc',
                                  'FGM2_Y_sc', 'FGM2_Z_sc', 'FGM3_X_sc', 'FGM3_Y_sc', 'FGM3_Z_sc', 'chaos7_b_fgm1_x',
                                  'chaos7_b_fgm1_y', 'chaos7_b_fgm1_z', 'chaos7_b_fgm2_x', 'chaos7_b_fgm2_y', 'chaos7_b_fgm2_z',
                                  'chaos7_b_fgm3_x', 'chaos7_b_fgm3_y', 'chaos7_b_fgm3_z', 'chaos7_b_sc_x', 'chaos7_b_sc_y',
                                  'chaos7_b_sc_z', 'q1_fgm12nec', 'q2_fgm12nec', 'q3_fgm12nec', 'q4_fgm12nec', 'q1_fgm22nec',
                                  'q2_fgm22nec', 'q3_fgm22nec', 'q4_fgm22nec', 'q1_fgm32nec', 'q2_fgm32nec', 'q3_fgm32nec',
                                  'q4_fgm32nec', 'lt', 'mjd2000', 'qdlat', 'qdlon', 'mlat', 'mlt',
]


