satellite_specifier: 'GOCE'

year_month_specifiers: ["201002"] # ["201001", "201002", "201003"] # ["200912"]

pandas_inplace: False
log_level: 'INFO' # 'DEBUG' # one of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'

goce_data_path: /Volumes/Crucial X8/GOCE/rawdata/ # Previously base_path
write_path: /Volumes/Crucial X8/satellite_intermediate3/

use_cache: False # True # False
auxiliary_data_path: ./data/auxiliary_params/
#space_weather_path: /Users/kevinstyp/Downloads/GOCE/all_kp_dst_indices_v3.lst
#amps_params_path: /Users/kevinstyp/Downloads/GOCE/amps_params.lst
hp30_path: /Users/kevinstyp/Downloads/GOCE/all_hp30.lst

orbit_counter_path: "/Volumes/Crucial X8/GOCE/ORBCNT/GO_ORBCNT_20090317T231001_20131109T234516_0101.h5"

model_output_path: "neuralnet/"
model_name: "pinn"
model_year_months: None

string_config_file: ???

string_conversion: 'one-hot' # or 'remove'

nan_share: 0.2

CDF-lib: "~/lib/"